### ISSUE TITLE
ECN Spray A references

### ISSUE THREAD

**Issue by kahilah** [Aalto-CFD/DLBFoam-Advanced-Tutorials#1]
I'd encourage you to include the following articles to be part of your references for the Spray A case as the implicit LES setup and most of the numerical setups are originating from the Authors' works and is peer-reviewed in the articles listed below.

Large Eddy Simulation of n-dodecane spray flames using Flamelet Generated Manifolds
http://www.sciencedirect.com/science/article/pii/S0010218016000754

Large-eddy simulation of dual-fuel ignition: Diesel spray injection into a lean methane-air mixture
https://linkinghub.elsevier.com/retrieve/pii/S0010218018304413

**Comment by mahgadalla** [comment]
Fixed by Commit c90338e803b916b375c680541991892792d3891a
