### ISSUE TITLE
Naming inconsistency in ECN Spray A tutorial

### ISSUE THREAD

**Issue by blttkgl** [Aalto-CFD/DLBFoam-Advanced-Tutorials#2]
In ECN Spray A tutorial, n-dodecane is used as "C12H26" in case setup, while as "NC12H26" in the thermo.foam and chem.foam files generated through ct2foam utility, making the tutorial crash. A consistency in naming required (with selecting the name with pre-compiled liquid properties exist) for the tutorial to work properly.

**Comment by mahgadalla** [comment]
Resolved by commit aff6b0356ee2143c6c82a5ecac493ee880965c7b
