### ISSUE TITLE
2D shear layer

### ISSUE THREAD

**Issue by banyangtju** [Aalto-CFD/DLBFoam-Advanced-Tutorials#8]
I have run the 2D shear layer cases, however, i cannot get the same result in the article or the results present in doc. 

Is there some change in the case setup? It is found that the NC12H26 mass fraction in this case (maximum 0.1) is different with that in the article (maximum 0.25).

**Comment by kjeevananthan** [comment]
There may be a typo. You can check with 0.25 value for NC12H26; it should work correctly. Additionally, ensure the values in the legend are accurately set, as this will alter the overall visual presentation.

**Comment by banyangtju** [comment]
Thanks for your reply. Do you mean that only set NC12H26 to 0.25? How about N2 O2 in the central zone? I noticed  NC12H26:N2:O2=1:7:2. In addition, the ambient premixed mixture denotes CH4/O2/N2/EGR. However, there is no EGR in the computational zone. How can users get a correct initial conditions?

**Comment by kjeevananthan** [comment]
Please use the initial conditions from Table 1 in https://www.sciencedirect.com/science/article/pii/S0016236123007135

**Comment by banyangtju** [comment]
Thanks for your reply. The concentration in Table 1 of https://www.sciencedirect.com/science/article/pii/S0016236123007135 may denotes the mass fraction.
